### ISSUE TITLE
"5- Shared-CoreData" doesn't build. Missing framework dependencies.

### ISSUE THREAD

**Issue by jessesquires** [kostiakoval/WatchKit-Apps#13]
Pulling straight from `master` the `5- Shared-CoreData` project doesn't build.

**Comment by kostiakoval** [comment]
@jessesquires  Thank for feedback. I'll have a look on it.
I have seen that issue but didn't know how to fix it. 
Maybe switching to cocoa pods would help

Know Issues:
- Could not build Objective-C module ... Select the framework target that couldn't be build and build it. The project dependencies are not build in correct order :(

**Comment by lucascorrea** [comment]
not working.

**Comment by kostiakoval** [comment]
yes that's true, I'm sorry :( 
There was an issue with frameworks linking. Not I'm updating examples to Watch OS 2.
